# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
executors:
  spring-executor:
    docker:
      - image: cimg/openjdk:17
jobs:
  build:
    executor: spring-executor
    steps:
      - checkout
      - run:
          name: Build Application
          command: mvn -B -DskipTests clean package # Build without running tests

workflows:
  version: 2.1
  build:
    jobs:
      - build:
         filters:
          branches:
            only:
              - main  # Change this to your default branch name